repos:
  - repo: local
    hooks:
      - id: pio-test
        name: pio-test
        entry: pio remote test
        language: system
        pass_filenames: false
        verbose: true
      - id: update-lib-version
        name: update-lib-version
        entry: node ./lib-version-check/lib-version-check.js
        language: node
